### ekf config file ###
ekf_filter_node:
    ros__parameters:

        use_sim_time: false
        
        frequency: 30.0
        two_d_mode: true
        publish_tf: true
        publish_acceleration: false
        print_diagnostics: true

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        odom0: diff_controller/odom
        odom0_differential: false
        odom0_relative: false

        imu0: imu_broadcaster/imu
        imu0_differential: false
        imu0_relative: true
 
        #        [x_pos   , y_pos    , z_pos,
        #         roll    , pitch    , yaw,
        #         x_vel   , y_vel    , z_vel,
        #         roll_vel, pitch_vel, yaw_vel,
        #         x_accel , y_accel  , z_accel]

        odom0_config: [false, false, false,
                       false, false, false,
                       true, true, false, 
                       false, false, true,
                       false, false, false]
               
        imu0_config: [false, false, false,
                      true, true, true,
                      false, false, false,
                      false, false, false,
                      false, false, false]
