joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.25
    autorepeat_rate: 20.0 # milliseconds

teleop_node: # PS4 Controller
  ros__parameters:
    axis_linear:
      x: 1 # Left stick vertical axis
    scale_linear:
      x: 0.4 # Scale factor for linear velocity
    scale_linear_turbo:
      x: 1.0 # Scale factor for linear velocity

    axis_angular:
      yaw: 0  # Left stick horizontal axis
    scale_angular:
      yaw: 0.5 # Scale factor for angular velocity
    scale_angular_turbo:
      yaw: 1.0 # Scale factor for angular velocity

    enable_button: 6 # left shoulder button
    enable_turbo_button: 7 # right shoulder button

    require_enable_button: true # Enable deadman switch, which helps with quickly stopping the robot

    publish_stamped_twist: true
