controller_manager: # Node name
  ros__parameters:
    update_rate: 30 # Has to be an integer otherwise errors are encountered

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    #imu_sensor_broadcaster:
      #type: imu_sensor_broadcaster/IMUSensorBroadcaster 


diff_controller:
  ros__parameters:
    
    publish_rate: 30.0 # Has to be a double otherwise errors are encountered

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.134
    wheel_radius: 0.0335

    # Whether the input has a time stamp or not
    use_stamped_vel: false

#imu_sensor_broadcaster:
#   ros__parameters:
#    sensor_name: mpu6050 
#    frame_id: imu_link


